### ISSUE TITLE
Ensure Bip32 path is shown to the User before address is displayed

### ISSUE THREAD

**Issue by zmanian** [binance-chain/ledger-app-binance#9]
Another upstream related security fix.

There is a ransom host compromise attack when malware inserts itself between the client software and ledger and generates a BIP32 unknown to the user.

We made changes to the upstream to ensure that only valid BP32 paths were sent and the paths were displayed to the user when generating addresses on device.

https://github.com/ZondaX/ledger-cosmos-app/pull/9/

**Comment by notatestuser** [comment]
Thanks @zmanian, 

Is there a reason why you chose to display the bip32 paths to users?

I would guess that it is possibly easier for people to check that an address looks ok (even if only comparing the last several chars of the checksum) rather than try to figure out what a bip32 path should be

Ledger wanted to have us show addresses on the device when displaying the receive screen in the wallet and possibly when signing too. Since this appears to be a UX requirement we will have to do something anyway.

Either way, these are great things to have for security.

**Comment by zmanian** [comment]
Yeah the usability of the bip32 path is an interesting question.

Here are the questions.

How does the user know if the address is for a key with a known BIP32 path? (i.e Looks Okay) if their machine is compromised?

**Comment by notatestuser** [comment]
They will select/confirm the address and its balance in the wallet, which would have to be compromised too to show a non okay address

Another option I can think of is to ask the user to select a numeric "challenge" / address number in the ledger app which is basically used as the last node(s) of the bip path.

**Comment by zmanian** [comment]
In the Cosmos App, we validate that all the nodes except the last two are the fundraiser nodes.

**Comment by notatestuser** [comment]
> In the Cosmos App, we validate that all the nodes except the last two are the fundraiser nodes.

Yes, great. This was [synced](https://github.com/binance-chain/ledger-app-binance/blame/master/src/app_main.c#L153) from Cosmos upstream one month ago.

---

As for the issue,

This has been addressed in v1.1.0 released a month ago (11th April).

We chose to take a different approach in the Binance app: Display the address to the user, and when confirmed (user presses device buttons), allow user to sign with that address.

We feel that this is more user friendly and tailored to our user base and UX requirements.

**Comment by notatestuser** [comment]
A bonus screenshot of the security feature:

![Screenshot 2019-05-08 at 12 43 10](https://user-images.githubusercontent.com/1255926/57350002-dd15d100-718e-11e9-9dac-de3e70c28136.png)

User is not able to sign unless they pass this step.
